# Generated by Django 3.1.7 on 2021-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0003_remove_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='part_of_a_day',
            field=models.CharField(choices=[('BR', 'Śniadanie'), ('DN', 'Obiad'), ('SP', 'Kolacja')], default='BR', max_length=2),
        ),
    ]
