# Generated by Django 3.1.7 on 2021-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0004_auto_20210322_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(max_length=1000),
        ),
    ]
