# Generated by Django 3.1.7 on 2021-03-25 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0005_auto_20210322_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='part_of_a_day',
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_need',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='day_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foddys.meal'),
        ),
    ]
