# Generated by Django 3.1.7 on 2021-03-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0006_auto_20210325_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='country_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foddys.worldcuisine'),
        ),
    ]
