# Generated by Django 3.1.7 on 2021-03-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0007_auto_20210325_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='country_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='foddys.worldcuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='day_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='foddys.meal'),
        ),
    ]
