# Generated by Django 3.1.7 on 2021-03-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0008_auto_20210325_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('ES', 'Łatwe'), ('MM', 'Średnie'), ('HR', 'Trudne')], default='ES', max_length=2),
        ),
    ]
