# Generated by Django 3.1.7 on 2021-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0010_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='defaultPhotox640.jpg', upload_to=''),
        ),
    ]
