# Generated by Django 3.1.7 on 2021-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foddys', '0014_auto_20210414_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='defaultRecipex640.jpg', upload_to=''),
        ),
    ]
